export interface HovCardH2Props {
    cardWidth?: string;
    cardHeight?: string;
    cardPadding?: string;
    cardBorderWidth?: string;
    cardBorderColor?: string;
    cardBorderStyle?: string;
    cardBorderRadius?: string;
    cardEndScale?: string;
    cardStartScale?: string;
    cardImgContent?: string;
    cardImgWidth?: string;
    cardImgHeight?: string;
    cardTitle?: string;
    cardTitleFontSize?: string;
    cardDescpriptionFontFamily?: string;
    cardDescpription?: string;
    cardRandomText?: string;
    cardBtnName1?: string;
    cardBtnName2?: string;
    cardBtnColor1?: string;
    cardBtnColor2?: string;
    cardBtnBackgroundColor1?: string;
    cardBtnBackgroundColor2?: string;
    cardBtnSize1?: string;
    cardBtnSize2?: string;
    cardBtnBorderRadius1?: string;
    cardBtnBorderRadius2?: string;
    onCustomClick1?: () => void;
    onCustomClick2?: () => void;
    cardSubtitle?: string;
    cardSubtitleEnable?: boolean;
    cardButton2Enabled?: boolean;
    cardBackgroundColor?: string;
    cardBackgroundBodyColor?: string;
    cardDescpriptionFontSize?: string;
    cardSubtitleFontSize?: string;
    cardBoxShadow?: string;
    cardBtnHeight1?: string;
    cardBtnHeight2?: string;
    cardBtnWidth1?: string;
    cardBtnWidth2?: string;
    isHoverEnabled?: boolean;
}
